### ISSUE TITLE
Settings.json 'failed to save' warning.

### ISSUE THREAD

**Issue by ianjanicki** [LinusU/vscode-auto-dark-mode#1]
Great extension! Works almost flawlessly on my Mac. When I'm actively using Code and my system automatically transitions to light/dark (via nightOwl), your extension works perfectly. But if my laptop has been sleeping, and I resume using Code, there is an open Settings.json tab and this warning 👇. I typically close the warning and the 'unsaved' Settings.json and it's fine — not sure why Code leaves it in this weird state.

MacOS: 10.14.1 (18B75)
Code: 1.29.1 (1.29.1)
Auto Dark Mode: 0.1.4

![screenshot 2019-01-01 11 10 52](https://user-images.githubusercontent.com/4295837/50575584-09bb7580-0db6-11e9-985d-94849d2ebcea.png)

**Comment by LinusU** [comment]
Yeah, I'm running into this as well (also using NightOwl btw 😍), I think it happens when having multiple windows open as well, or maybe a combination of the both 🤔 

I'm thinking that the problem _might_ be that the plugin is loaded once per window, and then all the windows try to update the settings file at the same time, resulting in the conflict...

**Comment by ianjanicki** [comment]
Good point. I need to experience it a few more times to deduce the cause. If I come up with something I'll make a PR.

**Comment by LinusU** [comment]
Could potentially guard the writes to settings using this package:

https://www.npmjs.com/package/proper-lockfile

**Comment by landoncope** [comment]
I believe this is happening when having multiple VSCode windows open, and not when waking from sleep.

**Comment by LinusU** [comment]
Should be fixed by 0fa76708faeec718cb61e8cc62d716efbe76e4c5, published as 0.1.5 🚀
