### ISSUE TITLE
Save current theme to config

### ISSUE THREAD

**Issue by EmaSuriano** [LinusU/vscode-auto-dark-mode#19]
Hello,

Great plugin here! I just want to know if there is a way to save the current theme into `setting.json` so I don't need to do it manually every time?

So for example, if I switched my light theme to `A`, then switch to dark mode and then when I go back to the light mode then I would love to use again the theme `A`. Currently, I have to set it manually.

Also, if it makes sense I can make a contribution to the plugin :)

**Comment by LinusU** [comment]
I'm not sure I understand exactly how you mean, if you set `autoDarkMode.lightTheme` to `A` then it should go back to `A` when you go to dark mode and back, is this not working for you?

**Comment by EmaSuriano** [comment]
I would love to have that every time I Switch the theme, then it will be automatically saved into the setting.json. or another way is to have the feature of Save to autoDark or autoLight.

This is because I normally use the shortcut to switch theme in vscode, and in case I change it I want to always that theme for the current config.

Does it make sense now?

**Comment by LinusU** [comment]
Ah I see, so basically you want it so that if you switch theme whilst this plugin is activated, it should see that and store that theme in either `autoDarkMode.lightTheme` or `autoDarkMode.darkTheme` depending on wether dark mode is activated or not.

This could be cool, although I'm not sure if there are any APIs for this. If there is a straight forward implementation that doesn't rely on any hacks, I would be happy to accept a PR.

That being said, dark mode theme switching is now a part of upstream VS Code, maybe the problem would be better solved there? 🤔

**Comment by EmaSuriano** [comment]
This feature has been introduced into VS code. No need to keep this issue.
